$(document).ready(function(){
  $("div").mouseover(function(){
    $(this).css({"border-style":"solid","border-color":"yellow","border-width":"3px"});
  });
  $("div").mouseout(function(){
    $("div").css("border-style","none");
  });
  $("#red").mouseover(function(){
    $("#green").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#green").mouseover(function(){
    $("#red").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#blue").mouseover(function(){
    $("#orange").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#orange").mouseover(function(){
    $("#blue").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#yellow").mouseover(function(){
    $("#purple").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#purple").mouseover(function(){
    $("#yellow").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#aquamarine").mouseover(function(){
    $("#vermillion").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#vermillion").mouseover(function(){
    $("#aquamarine").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#amber").mouseover(function(){
    $("#indigo").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#indigo").mouseover(function(){
    $("#amber").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#chartreuse").mouseover(function(){
    $("#magenta").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
  $("#magenta").mouseover(function(){
    $("#chartreuse").css({"border-style":"solid","border-color":"black","border-width":"3px"});
  });
});